num_gen: 0
epoch: 0
known_binding_site: 0
aurora: B
pdbid: 4af3
trained_model_path: trained_model_reduced_dataset_100_epochs
python_env_path: /vol/data/miniconda3/envs/graphbp_complete/bin/python
skip_generate: True
experiment: 0